### ISSUE TITLE
make_cluster_plot and make_gene_plot

### ISSUE THREAD

**Issue by MercedesBentata** [jackhump/leafviz#2]
Hello,

When trying to run either of these two function in R, my desired cluster or gene cannot be found.
These errors occur:
cluster_to_plot %in% cluster_ids is not TRUE
or
!is.null(exons_table) is not TRUE

When running these commands separately in R Console, the output is TRUE.
I have checked and my cluster/gene are on the final data.

Is there a way to fix this?

Thanks in advance!

**Comment by jackhump** [comment]
Hi Mercedes,

Just to check, are you loading in an RData file from Leafcutter first before running the functions?

Secondly, can you explain what you were doing to get these error messages? Does it work as a Shiny app and not on the command line? I haven't spent much time testing the individual functions on the command line as I wrote the plot functions to serve the app, rather than standalone.

If you show me an example using the example RData file I can try to replicate the error.

Best wishes,

Jack

**Comment by jackhump** [comment]
Hi Mercedes,

Any changes on your end?

**Comment by MercedesBentata** [comment]
Hey Jack,
Sorry I didn't get back to you sooner.
At the end, I used it in the command line and it worked fine.
I didn't continue checking in R.
Mercedes
